trash_collector/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
]

trash_collector/customers/urls.py
from django.urls import path

from . import views

# TODO: Determine what distinct pages are required for the customer user stories, add a path for each in urlpatterns

app_name = "customers"
urlpatterns = [
    path('', views.index, name="index"),
    path('new/', views.create, name="create")
]

trash_collector/employees/urls.py
from django.urls import path

from . import views

# TODO: Determine what distinct pages are required for the customer user stories, add a path for each in urlpatterns

app_name = "employees"
urlpatterns = [
    path('', views.index, name="index")
]

trash_collector/trash_collector/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # First adding our custom routes from our accounts app's urls.py (for our custom registration)
    path('accounts/', include('accounts.urls')),
    # Then adding django's built in routes (login and logout). Notice there is no login function in accounts/views.py
    path('accounts/', include('django.contrib.auth.urls')),
    # Adding all urls from customer app
    path('customers/', include('customers.urls')),
    # Adding all urls from employees app
    path('employees/', include('employees.urls')),
    # 'home' redirects a user to the appropriate index based on their auth group. Investigate views.py for more info
    path('', views.group_redirect, name='home')
]

trash_collector/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


class User(AbstractUser):
    """Our custom user model that adds a new field to the default django user model"""
    is_employee = models.BooleanField(default=False)

    def __str__(self):
        return self.username

trash_collector/customers/models.py
from django.db import models
from django.db.models.fields import CharField, DateField, IntegerField
from django import utils
import django.utils.timezone 

# Create your models here.

# TODO: Finish customer model by adding necessary properties to fulfill user stories


class Customer(models.Model):
    name = models.CharField(max_length=50)
    user = models.ForeignKey('accounts.User', blank=True, null=True, on_delete=models.CASCADE)
    street_address = models.CharField(blank=True, max_length=50)
    zip_code = models.CharField('customer.Zip Code', max_length=5)
    amount = models.IntegerField()
    weekly_pickup = models.CharField(default=True, null=True, max_length=50)
    one_time_pickup = models.DateField(default=django.utils.timezone.now, null=True)
    suspend_start = models.DateField(default=django.utils.timezone.now, null=True)
    suspend_end = models.DateField(default=django.utils.timezone.now, null=True)

    def __str__(self): 
        return self.name
    
    
 
 

trash_collector/employees/models.py
from django.db import models

# Create your models here.

# TODO: Create an Employee model with properties required by the user stories

trash_collector/accounts/forms.py
from django import forms
from .models import User
from django.contrib.auth.models import Group
from django.contrib.auth.forms import UserCreationForm


class CustomUserForm(UserCreationForm):
    """This form allows our custom user model to be registered with an added field reflecting its employee status"""
    is_employee = forms.BooleanField(label="Check to register as employee", required=False)

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "is_employee")

    def save(self, commit=True):
        # Overriding the save method to add user to auth group of Employee or Customer depending on if box is checked
        user = super(CustomUserForm, self).save(commit=False)
        user.is_employee = self.cleaned_data["is_employee"]

        # If you get an exception here, you need to create the Employee/Customer groups in the Admin interface
        if commit:
            user.save()
            if user.is_employee:
                employees = Group.objects.get(name="Employees")
                employees.user_set.add(user)
            else:
                customers = Group.objects.get(name="Customers")
                customers.user_set.add(user)
        return user

trash_collector/accounts/views.py
from django.contrib.auth import login
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.

from django.urls import reverse_lazy, reverse
from django.views import generic
from .forms import CustomUserForm


class RegisterView(generic.CreateView):
    """Allows user to register with the custom form we created"""
    form_class = CustomUserForm
    success_url = reverse_lazy('login')
    template_name = 'registration/register.html'

trash_collector/customers/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.apps import apps
from django.shortcuts import get_object_or_404
from .models import Customer
# Create your views here.

# TODO: Create a function for each path created in customers/urls.py. Each will need a template as well.


def index(request):
    # The following line will get the logged-in in user (if there is one) within any view function
    all_customers = Customer.objects.all()
    user = request.user()
    context = {
        'all_customers': all_customers
    }

    try:
        # This line inside the 'try' will return the customer record of the logged-in user if one exists
        logged_in_customer = Customer.objects.get(user=user)
    except:
        # TODO: Redirect the user to a 'create' function to finish the registration process if no customer record found
        
        return HttpResponseRedirect(reverse('customers:index.html', context))
    # It will be necessary while creating a Customer/Employee to assign request.user as the user foreign key
def create(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        street_address = request.POST.get('street_address')
        postal_code = request.POST.get('postal_code')
        weekly_pickup = request.POST.get('weekly_pickup')
        one_time_pickup = request.POST.get('one_time_pickup')
        suspend_start = request.POST.get('suspend_start')
        suspend_end = request.POST.get('suspend_end')
        new_customers = Customer(name=name,  street_address=street_address, postal_code=postal_code, weekly_pickup=weekly_pickup, one_time_pickup=one_time_pickup, suspend_start=suspend_start, suspend_end=suspend_end)
        new_customers.save()
        return HttpResponseRedirect(reverse('customers:index'))
    else:
        # print(user)
        return render(request, 'customers/index.html')
        

trash_collector/employees/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.apps import apps

# Create your views here.

# TODO: Create a function for each path created in employees/urls.py. Each will need a template as well.


def index(request):
    # This line will get the Customer model from the other app, it can now be used to query the db for Customers
    Customer = apps.get_model('customers.Customer')
    return render(request, 'employees/index.html')

trash_collector/trash_collector/views.py
from django.shortcuts import redirect, render


def group_redirect(request):
    """This single view function redirects a user to the customer or employee index if they are in either group"""
    if request.user.groups.filter(name="Customers").exists():
        return redirect('/customers/')
    elif request.user.groups.filter(name="Employees").exists():
        return redirect('/employees/')
    else:
        # If user is in neither group, get sent back to home
        return render(request, 'home.html')

trash_collector/customers/templates/customers/create.html
{% extends "base.html" %}

{% block title %}Create Page{% endblock %}

{% block header %}Customer Create{% endblock %}

{% block content %}
<form action="{% url 'customers:create' %}" method="post">
    {% csrf_token %}
    Name:<input type="text" name="name" id="name"><br>
    Street Address:<input type="text" name="street_address"><br>
    Zip Code:<input type="text" name="postal_code"><br>
    Amount:<input type="text" name="balance"><br>
    
    <!-- weekly_pickup = models.CharField(default=True, null=True, max_length=50)
    one_time_pickup = models.DateField(default=django.utils.timezone.now, null=True)
    suspend_start = models.DateField(default=django.utils.timezone.now, null=True)
    suspend_end = models.DateField(default=django.utils.timezone.now, null=True) -->
    Customer:
        <select name="customer" id="customer">
            {% for customer in all_customers %}
            <option value="{{customer.id}}">{{team}}</option>
            {% endfor %}
        </select>
    <input type="submit" value="Add new!">
</form>
{% endblock %}

trash_collector/customers/templates/customers/index.html
{% extends 'base.html' %}

{# This top line allows this template to utilizing the styling and layout from the base. All your templates should do the same. #}

{% block title %} Customer Home {% endblock %}

{% block header %} Customer Home {% endblock %}

{% block content %}
<ul>
  {% if user.is_authenticated %}
    Hello Customer {{ user.username }}!
  {% else %}
    <p>You are at the customer index, but you are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
  {% endif %}
  </ul>
{% endblock %}

trash_collector/employees/templates/employees/index.html
{% extends 'base.html' %}

{% block title %}{% block header %} Employee Home {% endblock %}{% endblock %}

{% block content %}
  {% if user.is_authenticated %}
    Hello Employee {{ user.username }}!
  {% else %}
    <p>You are at the employee index, but you are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
  {% endif %}
{% endblock %}

trash_collector/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% if user.is_authenticated %}
  {% for group in user.groups.all%}
    {% if group.name == "Customers" %}
    <p>Customer Navbar</p>
    {% elif group.name == "Employees" %}
    <p>Employee Navbar</p>
    {% endif %}
  {% endfor %}
  <p><a href="{% url 'logout' %}">Log Out</a></p>
{% endif %}
  <main>
    <h1>{% block header %} {% endblock %}</h1>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>
{# This is the parent template that should be extended by any other view you create #}
{# Todo: Add navbar links, link to stylesheets, style layout #}

trash_collector/templates/home.html
{% extends 'base.html' %}

{% block title %} Home Portal {% endblock %}

{% block header %} Home Portal {% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hello {{ user.username }}. You don't have a group assigned. Please contact administrator or attempt to register again.
  <p><a href="{% url 'logout' %}">Log Out</a></p>
{% else %}
  <p>You are not logged in. Please log in or create an account.</p>
  <a href="{% url 'login' %}">Log In</a>
  <a href="{% url 'accounts:register' %}">Sign Up</a>
{% endif %}
{% endblock %}

{# This is the home page that allows a logged out user to register or log in #}